include: package:lints/recommended.yaml

linter:
  rules:
    prefer_single_quotes: true
    prefer_final_locals: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    unnecessary_this: true
